---
title: "My first R Markdown report"
author: "Add your name here"
output: html_document
editor_options:
  chunk_output_type: console
---

# R markdown file

This an R Markdown file. It combines text with code. This is text written in plain markdown and you can use markdown syntax to highlight text in **bold**, *italic* or _underlined_.

# Tasks

I have listed tasks for you below. I am also going to show you how to solve the task on the shared screen. You can follow along as I speak. 

## Your turn 1 - Load necessary R packages

1. Let's add a code chunk by clicking on the green C+ at the top of this window
2. Inside the code chunk, write: library(tidyverse)
3. Click on the green play button in the top right of the code chunk you have created



**Delete this text and place the code chunk here**



## Your turn 2 - Import JMP WASH data

1. Add a new code chunk by clicking on the green C+ at the top of this window
2. Inside the code chunk, write: read_csv("data/washdata.csv")
3. Click on the green play button in the top right of the code chunk you have created

4. Inside the code chunk, on the same line as the current code, add: washdata <- 
5. Click on the green play button in the top right of the code chunk

6. In the top right pane, click on the tab "Environment"
7. Locate the data in the window and click on the text "washdata"



**Delete this text and place the code chunk here**



# Your turn 3 - Transform Data

1. Click on the green play button in the top right of the code chunk
2. Inspect the code that is written in the code chunk and try to identify what is happening
3. In the top right pane, click on the tab "Environment"
4. Locate the data in the window and click on the text "washdata_uga"

```{r}

washdata_uga <- washdata %>%
  filter(iso3 == "UGA") %>% 
  filter(year == 2017) %>% 
  filter(residence == "national") 
```

# Your Turn 4 - Communicate

1. Scroll to the top of the document and add your name inside the quotation marks "Add your name" next to author: 
2. Click on the Knit button (the blue yarn and needle emoticon on the top of this window) 

